version: '3'
services:
    web:
      build: ./sport-web
      command: nodemon
      ports:
        - "5000:5000"
      environment:
        - NODE_ENV=development
        - FOO=bar
      volumes:
        - ./sport-web:/app
        - /app/node_modules
      links: 
        - mongo
    mongo:
      image: mongo:latest
      ports:
        - 27017:27017
      